## 3.2 線形代数

### 3.2.1 スカラー

In [1]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5

### 3.2.2 ベクトル

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # 縦ベクトルとして扱う
b = np.array([-2.3, 0.25, -1.2, 1.8, 0.41])

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([-2.3 ,  0.25, -1.2 ,  1.8 ,  0.41])

### 3.2.3 行列

In [5]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3の行列
b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])  # 3x2の行列

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b

array([[ 0.21,  0.14],
       [-1.3 ,  0.81],
       [ 0.12, -2.1 ]])

### 3.2.4 テンソル

In [8]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
               [2, 3, 4, 5],
               [4, 5, 6, 7]],
              
              [[1, 2, 3, 4],
               [3, 4, 5, 6],
               [5, 6, 7, 8]]])  # (2, 3, 4)の3階のテンソル

In [9]:
a

array([[[0, 1, 2, 3],
        [2, 3, 4, 5],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [3, 4, 5, 6],
        [5, 6, 7, 8]]])

In [10]:
# 1階のテンソル（ベクトル）
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

# 2階のテンソル（行列）
b = b.reshape(4, 6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [11]:
# 3階のテンソル
b = b.reshape(2, 3, 4)
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
# 4階のテンソル
b = b.reshape(2, 2, 3, 2)
print(b)

[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]
   [17 18]]

  [[19 20]
   [21 22]
   [23 24]]]]


In [13]:
c = np.array([[[1,2,3,4],
               [2,0,0,0],
               [3,0,0,0]],
             
              [[2,0,0,0],
               [0,0,0,0],
               [0,0,0,0]]])  # (2, 3, 4)の3階のテンソル

In [14]:
# transposeメソッドによる軸の入れ替え1
c = c.transpose(0, 2, 1)  # (2, 4, 3)
print(c) 

[[[1 2 3]
  [2 0 0]
  [3 0 0]
  [4 0 0]]

 [[2 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [15]:
# transposeメソッドによる軸の入れ替え2
c = c.transpose(2, 0, 1)  # (3,2,4)
print(c) 

[[[1 2 3 4]
  [2 0 0 0]]

 [[2 0 0 0]
  [0 0 0 0]]

 [[3 0 0 0]
  [0 0 0 0]]]


In [16]:
# transposeメソッドによる軸の入れ替え3
c = c.transpose(1, 0, 2)  # (2, 3, 4)
print(c) 

[[[1 2 3 4]
  [2 0 0 0]
  [3 0 0 0]]

 [[2 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


### 3.2.5 スカラーと行列の積

In [17]:
import numpy as np

c = 2
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

print(c*a)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### 3.2.6 要素ごとの積

In [18]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 
b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]]) 

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [19]:
print(a+b)  # 足し算

[[0 2 4]
 [5 4 6]
 [7 9 8]]


In [20]:
print(a-b)  # 引き算

[[0 0 0]
 [1 4 4]
 [5 5 8]]


In [21]:
print(a/(b+1))  # 割り算 1を足すのはゼロ除算対策

[[0.         0.5        0.66666667]
 [1.         4.         2.5       ]
 [3.         2.33333333 8.        ]]


In [22]:
print(a%(b+1))  # 余り 1を足すのはゼロ除算対策

[[0 1 2]
 [0 0 1]
 [0 1 0]]


### 3.2.7 行列積

In [23]:
# dot関数による行列積の計算
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[2, 1],
              [2, 1],
              [2, 1]]) 

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [24]:
# 行列とベクトルの積
import numpy as np

a = np.array([1, 2, 3])  # （ベクトルは）行数1の行列として扱われる
b = np.array([[1, 2],
              [1, 2],
              [1, 2]])

print(np.dot(a, b))

[ 6 12]


### 3.2.8 行列の転置

In [25]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.T)  # 転置

[[1 4]
 [2 5]
 [3 6]]


In [26]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]])  # 2x3
b = np.array([[0, 1, 2],
              [1, 2, 3]])  # 2x3 このままでは行列積ができない

# print(np.dot(a, b))  # エラー
print(np.dot(a, b.T))  # 転置により行列積が可能に

[[ 5  8]
 [ 8 14]]
