## 2.4 Numpy

### 2.3.1 Numpyのインポート

In [1]:
import numpy as np

### 2.4.2 Numpyの配列

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [3]:
b = np.array([[0, 1, 2], [3, 4, 5]])  # リストのリストを渡す
print(b)

[[0 1 2]
 [3 4 5]]


In [4]:
c = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [5]:
print(np.shape(c))
print(np.size(c))

(2, 2, 3)
12


In [6]:
d = [[1,2],[3,4],[5,6]]  # (3, 2)
print(len(d))
print(len(np.array(d)))

3
3


### 2.4.3 配列を生成する様々な関数

In [7]:
print(np.zeros(10))
print(np.ones(10))
print(np.random.rand(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.20635951 0.99845721 0.39772604 0.9307375  0.21249415 0.95003015
 0.50220931 0.69967556 0.78489712 0.59884701]


In [8]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# arange(開始する値,終了する値,刻み幅)
print(np.arange(0, 1, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [11]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# linspace(開始する値,終了する値,要素数)
print(np.linspace(0, 1, 11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### 2.4.4 reshapeによる形状の変換

In [13]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])    # 配列の作成
b = a.reshape(2, 4)                       # (2, 4)の2次元配列に変換
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [14]:
c = b.reshape(2,2,2) # (2, 2, 2)の3次元配列に変換
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [15]:
d = c.reshape(4, 2) # (4, 2)の2次元配列に変換
print(d)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [16]:
e = d.reshape(-1) # 1次元配列に変換
print(e)

[0 1 2 3 4 5 6 7]


In [17]:
f = e.reshape(2, -1) # 要素を自動計算する
print(f)

[[0 1 2 3]
 [4 5 6 7]]


### 2.4.5 配列の演算

In [18]:
a = np.array([0, 1, 2, 3, 4, 5]).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [19]:
print(a + 3) # 各要素に3を足す

[[3 4 5]
 [6 7 8]]


In [20]:
print(a * 3) # 各要素に3をかける

[[ 0  3  6]
 [ 9 12 15]]


In [21]:
b = np.array([5, 4, 3, 2, 1, 0]).reshape(2, 3)
print(b)

[[5 4 3]
 [2 1 0]]


In [22]:
print(a + b)

[[5 5 5]
 [5 5 5]]


In [23]:
print(a * b)

[[0 4 6]
 [6 4 0]]


### 2.4.6 ブロードキャスト

In [24]:
a = np.array([[1, 1],
              [1, 1]])  # 2次元配列
b = np.array([1, 2])  # 1次元配列

In [25]:
print(a + b)

[[2 3]
 [2 3]]


In [26]:
c = np.array([[1],
              [2]])  # 2次元配列

In [27]:
print(a + c)

[[2 2]
 [3 3]]


### 2.4.7 要素へのアクセス

In [28]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[2])

2


In [29]:
a[2] = 9
print(a)

[0 1 9 3 4 5]


In [30]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])
print(b[1, 2])  # b[1][2]と同じ

5


In [31]:
b[1, 2] = 9
print(b)

[[0 1 2]
 [3 4 9]]


In [32]:
c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(c[1])  # インデックスが1つだけ

[3 4 5]


In [33]:
c[1] = np.array([9, 10, 11])  # 要素を配列で置き換え
print(c)

[[ 0  1  2]
 [ 9 10 11]
 [ 6  7  8]]


In [34]:
d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(d[d%2 == 0])  # [ ]内に条件を指定

[0 2 4 6 8]


In [40]:
e = np.zeros((3, 3))  # 2次元配列、要素は全て0
f = np.array([8, 9])  # 置き換える値

e[np.array([0, 2]), np.array([0, 1])] = f  # 2つの配列でインデッックスを指定
print(e)

[[8. 0. 0.]
 [0. 0. 0.]
 [0. 9. 0.]]


### 2.4.8 スライシング

In [41]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:8])  # スライシング

[2 3 4 5 6 7]


In [42]:
# ステップを指定する
print(a[2:8:2])

[2 4 6]


In [43]:
# すべての要素を指定する
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [51]:
b = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(b[0:2, 0:2])  # 各次元の範囲を指定

[[0 1]
 [3 4]]


In [52]:
b[0:2, 0:2] = np.array([[9, 9],
                        [9, 9]])  # 左上の領域を置き換え
print(b)

[[9 9 2]
 [9 9 5]
 [6 7 8]]


In [53]:
c = np.zeros(18).reshape(2, 3, 3)
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [54]:
c[0, 0:2, 0:2] =  np.ones(4).reshape(2, 2)
print(c)

[[[1. 1. 0.]
  [1. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### 2.4.9 軸とtranspose

In [55]:
a = np.array([[0, 1, 2],
              [3, 4, 5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [56]:
print(a.transpose(1, 0))  # 軸を入れ替え

[[0 3]
 [1 4]
 [2 5]]


In [57]:
print(a.T)  # 転置

[[0 3]
 [1 4]
 [2 5]]


In [58]:
b = np.arange(12).reshape(2, 2, 3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [59]:
print(b.transpose(1, 2, 0))

[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


### 2.4.10 NumPyの関数

In [60]:
# 配列のすべての要素の和
a = np.array([[0, 1],
              [2, 3]])
print(np.sum(a))

6


In [62]:
# 要素の縦方向の和
print(np.sum(a, axis=0))

[2 4]


In [63]:
# 要素の横方向の和
print(np.sum(a, axis=1))

[1 5]


In [64]:
# 次元数の保持
print(np.sum(a, axis=1, keepdims=True))

[[1]
 [5]]


In [65]:
print(np.max(a))

3


In [66]:
# 縦方向の最大値
print(np.max(a, axis=0))

[2 3]


In [67]:
# 　縦方向の最大値のインデックスを取得
print(np.argmax(a, axis=0))

[1 1]


In [68]:
print(np.where(a<2, 9, a))

[[9 9]
 [2 3]]
